### ISSUE TITLE
AttributeError: type object '_asyncio.Task' has no attribute 'all_tasks'

### ISSUE THREAD

**Issue by bruh1555** [NickWaterton/Roomba980-Python#130]
please help me
error:

   tasks = [t for t in asyncio.Task.all_tasks() if t is not asyncio.Task.current_task()]
                        ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object '_asyncio.Task' has no attribute 'all_tasks'

**Comment by NickWaterton** [comment]
What version of Python are you using? This is likely the issue. `asyncio.Task.all_tasks()` was removed in Python 3.7. Replaced by `asyncio.all_tasks()`.

**Comment by bruh1555** [comment]
I am running python 3.12.4. Also, am i able to run this code on a roomba 694? I have to run it on my newer version because if i run it on the roomba 694 it gives me this error: Connection Error: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1000) 
Attempting retry Connection# 0
Connection Error: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1000) 
Attempting retry Connection# 1
Connection Error: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1000) 
Attempting retry Connection# 2
Connection Error: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1000)

**Comment by bruh1555** [comment]
Ah, fixed it, both of them. All i had to do was change some ssh rules and change the line to what you said. Thanks!
