### ISSUE TITLE
Too verbose logging in INFO level

### ISSUE THREAD

**Issue by PaulAnnekov** [NickWaterton/Roomba980-Python#20]
Home Assistant (HA) is using this library and due to too verbose logging in `INFO` level the console is full of `roombapy` logs. [Here is](https://github.com/home-assistant/home-assistant/issues/10283) related issue in HA.

As I can see in `roomba.py`, most of `log.info` can be converted to `log.debug`, because these logs are not user-friendly and intended for developers.

@pschmitt I see you maintain `roombapy` package, so this issue is related to your fork too.

**Comment by pschmitt** [comment]
I fixed this issue in roombapy: 3026921d6c4cc59959c521513a15057004b25723

**Comment by PaulAnnekov** [comment]
Great! Thank you.

**Comment by PaulAnnekov** [comment]
@pschmitt so what about a PR to HA? As I understand you need to release a new version of roombapy and make a PR with version update in HA.
