### ISSUE TITLE
Performance Optimisations

### ISSUE THREAD

**Issue by HolgerHees** [NickWaterton/Roomba980-Python#29]
Hello,

I run your program on a low power Celeron J4105 powered board and it is running with ~50% CPU utilization if the roomba is active.

Now I tried to optimize it a little bit.

1. I disabled the storage of the lines.png and the problems.png. I use it as a in memory only image.
2. I apply the problems.png only if there are problems.
3. I disabled the map.png because I use the map_notext.png only. I will make this configureable

as a result, the utilization is going down from 50-60% to 18-20%.

Is there any reason why you are storing the lines.png and the problems.png on the harddisk?

Later I can also provide a pull request.

**Comment by NickWaterton** [comment]
No real reason, but I have a SSD and a fairly powerful server, so I didnt really notice (OpenCV processing uses a fair amount of processing power though).

CPU usage optimization would be welcome.
