### ISSUE TITLE
Voltage

### ISSUE THREAD

**Issue by wojtulab** [NickWaterton/Roomba980-Python#31]
Hi, is it possibile to get current voltage ? (900 series)

**Comment by NickWaterton** [comment]
What exactly do you mean by voltage? Voltage of what? We get battery % not voltage, but you could convert that to voltage if you know the max battery voltage.

What would you use voltage for?

**Comment by wojtulab** [comment]
I changed battery. For now roomba works only 60-70min. I would like to meassure battery voltage.

**Comment by NickWaterton** [comment]
That's what battery % is. My Roomba battery life dropped after a year of daily use, so I replaced the battery, back to 2 hours plus usage now.

To answer your question, the battery % shown is derived from battery voltage. I don't have access to the raw battery voltage, just the derived % value.
