### ISSUE TITLE
Reconnect issues

### ISSUE THREAD

**Issue by QServ** [NickWaterton/Roomba980-Python#35]
I’m have a problem that I can’t reconnect to my Roomba if the connection is lost.
According to the log it tries to reconnect but nothing happens. 
If I restart roompa.py I get connection refused. 
I always have to restart my Roomba to be able to connect to it again.

**Comment by QServ** [comment]
I have firmware version 2.4.4-4.
I had the same issue with dotita980 but I thought it was the docker image that was acting up.
Does anyone else have this issue?

**Comment by NickWaterton** [comment]
When you say connect, are you talking about the mqtt connection, or wifi connection?

**Comment by QServ** [comment]
It is the mqtt connection. I can ping the roomba but the roomba script gets connection refused.
From the syslog:
`
Jun 11 22:15:59 roomba[26869]: [I 2018-06-11 22:15:59,380] *******************
Jun 11 22:15:59 roomba[26869]: [I 2018-06-11 22:15:59,380] * Program Started *
Jun 11 22:15:59 roomba[26869]: [I 2018-06-11 22:15:59,380] *******************
Jun 11 22:15:59 roomba[26869]: [I 2018-06-11 22:15:59,380] Roomba.py Version: 1.2.1
Jun 11 22:15:59 roomba[26869]: [I 2018-06-11 22:15:59,381] Python Version: 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
Jun 11 22:15:59 roomba[26869]: [I 2018-06-11 22:15:59,381] Paho MQTT Version: 1.3.1
Jun 11 22:15:59 roomba[26869]: [I 2018-06-11 22:15:59,381] CV Version: 3.4.1
Jun 11 22:15:59 roomba[26869]: [I 2018-06-11 22:15:59,381] <CNTRL C> to Exit
Jun 11 22:15:59 roomba[26869]: [I 2018-06-11 22:15:59,381] Roomba 980 MQTT data Interface
Jun 11 22:15:59 roomba[26869]: [I 2018-06-11 22:15:59,382] reading info from config file ./config.ini
Jun 11 22:15:59 roomba[26869]: [I 2018-06-11 22:15:59,383] connecting to broker
Jun 11 22:15:59 roomba[26869]: [I 2018-06-11 22:15:59,383] Creating Roomba object 192.168.0.36
Jun 11 22:15:59 roomba[26869]: [I 2018-06-11 22:15:59,383] CONTINUOUS connection
Jun 11 22:15:59 roomba[26869]: [I 2018-06-11 22:15:59,383] connecting Roomba 192.168.0.36
Jun 11 22:15:59 roomba[26869]: [I 2018-06-11 22:15:59,384] Posting DECODED data
Jun 11 22:15:59 roomba[26869]: [I 2018-06-11 22:15:59,384] MAP: Maps Enabled
Jun 11 22:15:59 roomba[26869]: [I 2018-06-11 22:15:59,384] MAP: openening existing line image
Jun 11 22:15:59 roomba[26869]: [I 2018-06-11 22:15:59,435] MAP: openening existing problems image
Jun 11 22:15:59 roomba[26869]: [I 2018-06-11 22:15:59,474] MAP: openening existing map no text image
Jun 11 22:15:59 roomba[26869]: [I 2018-06-11 22:15:59,526] MAP: home_pos: (700,0)
Jun 11 22:15:59 roomba[26869]: [I 2018-06-11 22:15:59,537] MAP: Initialisation complete
Jun 11 22:15:59 roomba[26869]: [I 2018-06-11 22:15:59,538] Connecting Roomba
Jun 11 22:15:59 roomba[26869]: [I 2018-06-11 22:15:59,538] Seting TLS
Jun 11 22:15:59 roomba[26869]: [E 2018-06-11 22:15:59,548] Error: [Errno 111] Connection refused
Jun 11 22:15:59 roomba[26869]: [E 2018-06-11 22:15:59,548] Attempting new Connection# 1
Jun 11 22:16:00 roomba[26869]: [I 2018-06-11 22:16:00,549] Connecting Roomba
Jun 11 22:16:00 roomba[26869]: [E 2018-06-11 22:16:00,551] Error: [Errno 111] Connection refused
Jun 11 22:16:00 roomba[26869]: [E 2018-06-11 22:16:00,551] Attempting new Connection# 2
Jun 11 22:16:01 roomba[26869]: [I 2018-06-11 22:16:01,552] Connecting Roomba
Jun 11 22:16:01 roomba[26869]: [E 2018-06-11 22:16:01,554] Error: [Errno 111] Connection refused
Jun 11 22:16:01 roomba[26869]: [E 2018-06-11 22:16:01,554] Attempting new Connection# 3
Jun 11 22:16:02 roomba[26869]: [I 2018-06-11 22:16:02,555] Connecting Roomba
Jun 11 22:16:02 roomba[26869]: [E 2018-06-11 22:16:02,556] Error: [Errno 111] Connection refused
Jun 11 22:16:02 roomba[26869]: [E 2018-06-11 22:16:02,556] Unable to connect Roomba
`

**Comment by QServ** [comment]
After some network snuffing I discovered that the old rest980 docker image on an old host had started up again for some reason. It was hogging the connection. I need to go through my boot scripts...
Sorry for the trouble.
