### ISSUE TITLE
OpenHab + Roomba not listening to commands

### ISSUE THREAD

**Issue by gregorij89** [NickWaterton/Roomba980-Python#44]
Hello, this is more like the question than a bug, but honestly, I don´t know where to post it elsewhere.  I am interested in connecting my Roomba 960 with OpenHab instance. I´ve downloaded your script and successfully initialized it. So when I run "roomba" it connects to my Roomba and provides me with some feedback about configuration, and that wifi is on and Roomba is in dock etc. But when I try to send a command to my Roomba, either by roomba -C "start" or by trying your simple Python script example, nothing happens.

Secondly, I cannot figure out, how to set up OpenHab to support Roomba. Particularly, how to set up a connection to the MQTT broker. Right now, in my mqtt.cfg I have:

proliant.url=ssl://10.10.64.127:8883 // Roomba IP
proliant.clientId=3165010C82110820
proliant.user=3165010C82110820
proliant.pwd=:1:1539180234:X5DYZpWd7DPcGFvB

but OpenHab fails to connect to the Roomba. Could you please provide me with an example of mqtt.cfg? I was unable to find it in your GIT store.

Thanks in advance.
George

**Comment by NickWaterton** [comment]
George,

You seem to be doing things very differently to what I intended when I created the Roomba interface for OH2. This is supposed to be a very simple configuration, which you are fundamentally misunderstanding.

The roomba.py program is intended to be a bridge from the Roomba mqtt server to _your own_ mqtt server. The Roomba mqtt server only allows one connection, so my program connects to the Roomba mqtt server (and takes care of the login, password, TLS encryption, certificates etc), then bidirectionally forwards the Roomba mqtt messages to your own mqtt server, decoding/encoding the json in the process. You then use the OH2 mqtt binding to bind items to _your own_ mqtt server topics decoded from the Roomba messages.

> each json item is decoded and published as a separate topic. To see the topic published and their values run: `mosquitto_sub -v -t /roomba/feedback/#`

So the first step is to set up your own mqtt server. What platform are you running OH2 on?

The problem starts with the mqtt.cfg settings. On my system, this is configuring **my** mqtt server, nothing to do with the Roomba at all. proliant is my server name (which is what OH2 is running on).

You seem to be trying to set OH2's mqtt server source to be the Roomba itself - which will not work, as the roomba is sending/receiving json, not text.

So, How to control Roomba from OH2:

1. Set up your own mqtt server (Ubuntu/raspian/debian `sudo apt-get install mosquitto mosquitto-clients`)
2. install the OH2 mqtt binding
3. Configure OH2 mqtt.cfg with your own mqtt server settings.
example:
```
myservername.url=tcp://localhost:1883 // or my mqtt server IP if it's not the localhost
myservername.clientId=Openhab2Connection //any unique label to identify the connection
//myservername.user=user //optional, not created by default
//myservername.pwd=passwd //optional, not created by default
```
leave out user name and password if you have not created an mqtt user or password for your mqtt server, these are not created by default.
4. Run roomba.py (include options for your own mqtt server if needed, ip, port, user, password - the defaults work for simple installs, so you can leave them out) - messages should now be passed back and forth between the roomba, and your own mqtt server (you can see them in the log), and you can check what your mqtt server is receiving using `mosquitto_sub -v -t /roomba/feedback/#` (with -h ip if the server is not on your localhost).
5. Configure OH2 items to bind to your own mqtt server messages as shown in the OH2 examples.

Hope this explains the usage, In my explanation in the ReadMe, I am assuming that you have your own mqtt broker already running, probably a bad assumption on my part.

Let me know how you get on.

**Comment by gregorij89** [comment]
Ok, now I am feeling embarrassed. I already had my MQTT up and running before I´ve started to play with your script. But somehow, the concept that the script is actually a "translator" from Roomba MQTT to another MQTT missed me.

So now, when I finally understand the usage of your script (yes, I was questioning myself Why the hell is there this script if OpenHab connects to the Roomba directly), I am able to control my Roomba from OpenHab. So thanks for your post, it clears the thing.

One more comment from my side. Is somehow possible to disable the logging to the file? I see only the possibility to specify a file, but honestly, this file will grow beyond the limits during the time (I´ve set up the script as a daemon - service, so it runs 24/7). It is producing 1.6 MB file per hour.

So thank you for your post and also for your great job.

George

**Comment by NickWaterton** [comment]
No Problem, chalk it up to bad documentation.

As to logging, I have had some people complain about the logging (can't help it - I'm a logger!). The file will not get too huge, it's set up to use rotating files, so each log file is limited to 2 Mbytes in size, and it only keeps the last 5 log files - total size of all the logs cannot exceed 10 MBytes.

I also run the script as a daemon, and have been running it for 18 months without any issues.

In some of my later programs, I added the option to specify 'None' for the log file, and it disables logging (but I don't think I have that feature in this one). You could try `/dev/null` as the file name (haven't tried it, but that is where I send things I don't want). Might not work though.

The final thing you could try, if you are willing to hack the program a bit is to find the lines:
```
    if arg.debug:
        log_level = logging.DEBUG
    else:
        log_level = logging.INFO
```
in roomba.py (or maybe Main.py I forget where this ends up) and change the log level from `INFO` to `WARN` or `ERROR`, then the logs would only log warnings or errors, and not info.

Or just don't care, it's only 10 Mbytes.
