### ISSUE TITLE
missing comma

### ISSUE THREAD

**Issue by klaudiusz223** [NickWaterton/Roomba980-Python#72]
https://github.com/NickWaterton/Roomba980-Python/blob/959a6bc145d38874bb14ba72a469ab98ac70efbf/roomba/roomba.py#L159

**Comment by starmman** [comment]
just found that one too - didn't notice it was a syntax error and thought my roomba had a docking issue as there was a pram parked behind it =)

**Comment by matheus2308** [comment]
Wow good catch, I was also having issues and after fixing this, it worked for me!

#73

**Comment by NickWaterton** [comment]
Sorry guy's, missed that.
