### ISSUE TITLE
5 minute pause not working

### ISSUE THREAD

**Issue by mbakker** [NickWaterton/Roomba980-Python#90]
I have installed this on my Ubuntu machine and it's working however the loop to update the device status runs without pausing, you can see from the below log that it's running every few seconds instead of every 5 minute as designed.

May 19 22:22:14 <server> python3[608256]: 2021-05-19 22:22:14,703 - Roomba.roomba - INFO - current_state: Charging, current phase: charge, mission: none, mission_min: 0, recharge_min: 0, co-ords changed: False
May 19 22:22:20 <server> python3[608256]: 2021-05-19 22:22:20,876 - Roomba.roomba - INFO - current_state: Charging, current phase: charge, mission: none, mission_min: 0, recharge_min: 0, co-ords changed: False
May 19 22:22:27 <server> python3[608256]: 2021-05-19 22:22:27,462 - Roomba.roomba - INFO - current_state: Charging, current phase: charge, mission: none, mission_min: 0, recharge_min: 0, co-ords changed: False
May 19 22:22:33 <server> python3[608256]: 2021-05-19 22:22:33,251 - Roomba.roomba - INFO - current_state: Charging, current phase: charge, mission: none, mission_min: 0, recharge_min: 0, co-ords changed: False
May 19 22:22:39 <server> python3[608256]: 2021-05-19 22:22:39,441 - Roomba.roomba - INFO - current_state: Charging, current phase: charge, mission: none, mission_min: 0, recharge_min: 0, co-ords changed: False
May 19 22:22:45 <server> python3[608256]: 2021-05-19 22:22:45,624 - Roomba.roomba - INFO - current_state: Charging, current phase: charge, mission: none, mission_min: 0, recharge_min: 0, co-ords changed: False
May 19 22:22:51 <server> python3[608256]: 2021-05-19 22:22:51,814 - Roomba.roomba - INFO - current_state: Charging, current phase: charge, mission: none, mission_min: 0, recharge_min: 0, co-ords changed: False
May 19 22:22:58 <server> python3[608256]: 2021-05-19 22:22:58,403 - Roomba.roomba - INFO - current_state: Charging, current phase: charge, mission: none, mission_min: 0, recharge_min: 0, co-ords changed: False
May 19 22:23:04 <server> python3[608256]: 2021-05-19 22:23:04,188 - Roomba.roomba - INFO - current_state: Charging, current phase: charge, mission: none, mission_min: 0, recharge_min: 0, co-ords changed: False

Python version is: 3.8.5

Thanks for your help....
Marc

**Comment by NickWaterton** [comment]
This is how it is supposed to work,

The log is just reporting the current status every time the Roomba updates it's status (every 5 seconds or so - depends on the Roomba).

'Publishing' means via MQTT, logging is not publishing.

This is also not the same thing as publishing the full status every 5 minutes. Full status is dozens of values, like software version, total mission hours, scheduled jobs etc etc.

**Comment by mbakker** [comment]
Thanks for clarifying.
