### ISSUE TITLE
Get the room name

### ISSUE THREAD

**Issue by FilipDem** [NickWaterton/Roomba980-Python#91]
Hi,

I am looking for a way to get the room name (for Roomba's supporting rooms) when the Roomba is running.
Is there is any MQTT status (I didn't found) or an function to get the room name?

Use case is simple: I integrated with Domoticz and have some camera's sending warnings in case of movement... Of course if the roomba is passing, alarms are sent out. So want to automatically switch of the camera alarm when the roomba is cleaning in the room.

Thanks,

Filip

**Comment by NickWaterton** [comment]
No, sorry,

The only thing Roomba reports when running is the x,y co-ordinates (and things like 'bin full', 'docking' etc).

The only way to figure out what room the Roomba is in is to compare the x,y co-ordinates with a floor plan, and translate that into a room name yourself. Not easy, but doable.

**Comment by FilipDem** [comment]
Thanks, Nick,

I know it is doable, but wanted to work with the room names to avoid having to calculate also the coordinates of the floor plan myself.

Thanks for your answer. You confirmed that I need to implement it myself... Will give it a try when I have a bit of time.

Btw: you did a great job with the implementation.

Filip
