### ISSUE TITLE
What kind of commands are available?

### ISSUE THREAD

**Issue by MoriYu0011** [NickWaterton/Roomba980-Python#93]
I know the following commands are available.

```
"start"
"stop"
"pause"
"resume"
"dock"
"evac" (only with clean base)
"reset"
"locate"
```

Does anyone know any other commands? I want to use basic commands such as
* `rotate 30 degree`,
* `go straight (1 feet)`, and so on.

**Comment by NickWaterton** [comment]
Sorry, Roomba doesn't support those kind of commands.

The experimental robot Create 2 does that https://store.irobot.com/default/create-programmable-programmable-robot-irobot-create-2/RC65099.html.

**Comment by MoriYu0011** [comment]
Thanks so much!
