### ISSUE TITLE
Problem getting Password

### ISSUE THREAD

**Issue by kiatchun** [NickWaterton/Roomba980-Python#98]
This is what I get when I try to get the password. It is a similar error for this script and any other script I try. 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/93459510/144187361-9587ceba-3ceb-4dc4-a6bf-b63b33a81d61.png">

**Comment by kiatchun** [comment]
Update: I just needed to use a older version of python without the ssl patch.

**Comment by NickWaterton** [comment]
What version of python were you using? This is actually an OS issue. Ubuntu changed the default minimum TLS version in 20.04, which causes this error.

Are you using Ubuntu 20.04?

**Comment by kiatchun** [comment]
I was using windows. Downgrading from Python 3.10 to Python 3.9 fixed it.
